export const SUPABASE_MIGRATIONS_DIR = "supabase/migrations";

export const SUPABASE_MIGRATIONS = Object.freeze([
  Object.freeze({
    id: "initial_schema_base",
    version: "20260404000000",
    name: "initial_schema_base",
    file: "supabase/migrations/20260404000000_initial_schema_base.sql",
    legacySources: Object.freeze(["db/schema.sql"]),
    tier: "foundation",
    note: "Bootstrap baseline for pre-CLI projects. Covers the pre-increment foundation only so later ordered migrations still carry the real schema history.",
  }),
  Object.freeze({
    id: "owner_access",
    version: "20260404000100",
    name: "owner_access",
    file: "supabase/migrations/20260404000100_owner_access.sql",
    legacySources: Object.freeze(["db/owner_access.sql"]),
    tier: "full-current-main",
    note: "Adds agents.owner_user_id and access_status. Required before action queue ownership backfills when legacy databases are behind.",
  }),
  Object.freeze({
    id: "messages_visitor_identity",
    version: "20260404000200",
    name: "messages_visitor_identity",
    file: "supabase/migrations/20260404000200_messages_visitor_identity.sql",
    legacySources: Object.freeze(["db/messages_visitor_identity.sql"]),
    tier: "startup-critical",
    note: "Adds messages.session_key for startup-safe message persistence and session-aware chat history.",
  }),
  Object.freeze({
    id: "message_visitor_identity_fields",
    version: "20260404000201",
    name: "message_visitor_identity_fields",
    file: "supabase/migrations/20260404000201_message_visitor_identity_fields.sql",
    legacySources: Object.freeze([]),
    tier: "startup-critical",
    note: "Adds durable visitor identity fields to existing messages tables when the earlier session-key migration was already applied in production.",
  }),
  Object.freeze({
    id: "install_verification_activation_loop",
    version: "20260404000300",
    name: "install_verification_activation_loop",
    file: "supabase/migrations/20260404000300_install_verification_activation_loop.sql",
    legacySources: Object.freeze(["db/install_verification_activation_loop.sql"]),
    tier: "startup-critical",
    note: "Adds install verification fields plus agent_widget_events telemetry storage required by startup install and widget telemetry probes.",
  }),
  Object.freeze({
    id: "live_conversion_loop",
    version: "20260404000400",
    name: "live_conversion_loop",
    file: "supabase/migrations/20260404000400_live_conversion_loop.sql",
    legacySources: Object.freeze(["db/live_conversion_loop.sql"]),
    tier: "startup-critical",
    note: "Adds agent_contact_leads for live lead capture. Required by startup lead-capture validation.",
  }),
  Object.freeze({
    id: "action_queue_statuses",
    version: "20260404000500",
    name: "action_queue_statuses",
    file: "supabase/migrations/20260404000500_action_queue_statuses.sql",
    legacySources: Object.freeze(["db/action_queue_statuses.sql"]),
    tier: "startup-critical",
    note: "Adds owner-scoped action queue persistence used during startup. Legacy backfill behavior depends on owner_access already existing.",
  }),
  Object.freeze({
    id: "agent_follow_up_workflows",
    version: "20260404000600",
    name: "agent_follow_up_workflows",
    file: "supabase/migrations/20260404000600_agent_follow_up_workflows.sql",
    legacySources: Object.freeze(["db/agent_follow_up_workflows.sql"]),
    tier: "startup-critical",
    note: "Adds follow-up workflow persistence required by startup workflow validation.",
  }),
  Object.freeze({
    id: "agent_knowledge_fix_workflows",
    version: "20260404000700",
    name: "agent_knowledge_fix_workflows",
    file: "supabase/migrations/20260404000700_agent_knowledge_fix_workflows.sql",
    legacySources: Object.freeze(["db/agent_knowledge_fix_workflows.sql"]),
    tier: "startup-critical",
    note: "Adds knowledge-fix workflow persistence required by startup workflow validation.",
  }),
  Object.freeze({
    id: "conversion_outcomes",
    version: "20260404000800",
    name: "conversion_outcomes",
    file: "supabase/migrations/20260404000800_conversion_outcomes.sql",
    legacySources: Object.freeze(["db/conversion_outcomes.sql"]),
    tier: "startup-critical",
    note: "Adds agent_conversion_outcomes and success URL persistence required by startup conversion outcome validation.",
  }),
  Object.freeze({
    id: "direct_conversion_routing",
    version: "20260404000900",
    name: "direct_conversion_routing",
    file: "supabase/migrations/20260404000900_direct_conversion_routing.sql",
    legacySources: Object.freeze(["db/direct_conversion_routing.sql"]),
    tier: "feature-gated",
    note: "Adds direct CTA routing fields on widget_configs. Useful for routing behavior, but not required to boot current main.",
  }),
  Object.freeze({
    id: "connected_operator_workspace",
    version: "20260404001000",
    name: "connected_operator_workspace",
    file: "supabase/migrations/20260404001000_connected_operator_workspace.sql",
    legacySources: Object.freeze(["db/connected_operator_workspace.sql"]),
    tier: "operator-only",
    note: "Adds Google/operator inbox, calendar, and campaign workspace tables. Operator-only and not startup-critical.",
  }),
  Object.freeze({
    id: "contacts_people_workspace",
    version: "20260404001100",
    name: "contacts_people_workspace",
    file: "supabase/migrations/20260404001100_contacts_people_workspace.sql",
    legacySources: Object.freeze(["db/contacts_people_workspace.sql"]),
    tier: "operator-only",
    note: "Adds operator contact graph tables and contact foreign keys across operator flows. Operator-only and not startup-critical.",
  }),
  Object.freeze({
    id: "cross_channel_outcomes",
    version: "20260404001200",
    name: "cross_channel_outcomes",
    file: "supabase/migrations/20260404001200_cross_channel_outcomes.sql",
    legacySources: Object.freeze(["db/cross_channel_outcomes.sql"]),
    tier: "operator-only",
    note: "Extends conversion outcomes with cross-channel operator attribution fields. Operator-only and not startup-critical.",
  }),
  Object.freeze({
    id: "operator_business_profiles",
    version: "20260404001300",
    name: "operator_business_profiles",
    file: "supabase/migrations/20260404001300_operator_business_profiles.sql",
    legacySources: Object.freeze(["db/operator_business_profiles.sql"]),
    tier: "operator-only",
    note: "Adds durable operator-focused business profile context for Today + Copilot summaries and approval-first drafts.",
  }),
  Object.freeze({
    id: "copilot_proposal_states",
    version: "20260404001400",
    name: "copilot_proposal_states",
    file: "supabase/migrations/20260404001400_copilot_proposal_states.sql",
    legacySources: Object.freeze(["db/copilot_proposal_states.sql"]),
    tier: "operator-only",
    note: "Adds lightweight proposal state persistence so Today Copilot can hide applied or dismissed proposals without autonomous execution.",
  }),
  Object.freeze({
    id: "widget_logo_url",
    version: "20260416000000",
    name: "widget_logo_url",
    file: "supabase/migrations/20260416000000_widget_logo_url.sql",
    legacySources: Object.freeze(["db/widget_logo_url.sql"]),
    tier: "feature-gated",
    note: "Adds optional widget logo image persistence for customer-facing widget header branding.",
  }),
  Object.freeze({
    id: "dashboard_language_preferences",
    version: "20260422000000",
    name: "dashboard_language_preferences",
    file: "supabase/migrations/20260422000000_dashboard_language_preferences.sql",
    legacySources: Object.freeze(["db/dashboard_language_preferences.sql"]),
    tier: "feature-gated",
    note: "Adds owner-level dashboard language preference storage for the logged-in app. The dashboard can fall back to cached English/Hungarian preferences if this table is not present yet.",
  }),
  Object.freeze({
    id: "billing_plans_ai_usage",
    version: "20260428000000",
    name: "billing_plans_ai_usage",
    file: "supabase/migrations/20260428000000_billing_plans_ai_usage.sql",
    legacySources: Object.freeze(["db/billing_plans_ai_usage.sql"]),
    tier: "startup-critical",
    note: "Adds owner billing plan state plus per-period AI usage ledger storage for subscription enforcement, warnings, and monthly capacity caps.",
  }),
  Object.freeze({
    id: "business_vertical",
    version: "20260510000000",
    name: "business_vertical",
    file: "supabase/migrations/20260510000000_business_vertical.sql",
    legacySources: Object.freeze(["db/business_vertical.sql"]),
    tier: "feature-gated",
    note: "Adds businesses.vertical for industry-specific front-desk prompt templates and owner setup controls.",
  }),
  Object.freeze({
    id: "rls_hardening",
    version: "20260510001000",
    name: "rls_hardening",
    file: "supabase/migrations/20260510001000_rls_hardening.sql",
    legacySources: Object.freeze([]),
    tier: "foundation",
    note: "Enables RLS across public app tables and adds owner-scoped authenticated policies for direct owner/customer table access.",
  }),
  Object.freeze({
    id: "visitor_reply_feedback",
    version: "20260510002000",
    name: "visitor_reply_feedback",
    file: "supabase/migrations/20260510002000_visitor_reply_feedback.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds assistant reply helpful/not-helpful feedback storage keyed by agent, session, and assistant message.",
  }),
  Object.freeze({
    id: "customer_value_trust_controls",
    version: "20260510003000",
    name: "customer_value_trust_controls",
    file: "supabase/migrations/20260510003000_customer_value_trust_controls.sql",
    legacySources: Object.freeze(["db/customer_value_trust_controls.sql"]),
    tier: "feature-gated",
    note: "Adds owner-facing human follow-up statuses, notification dedupe/status, and privacy retention preferences.",
  }),
  Object.freeze({
    id: "product_events_owner_dedupe",
    version: "20260511090000",
    name: "product_events_owner_dedupe",
    file: "supabase/migrations/20260511090000_product_events_owner_dedupe.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner context and first-event dedupe keys to internal product events without changing public analytics providers.",
  }),
  Object.freeze({
    id: "activation_wizard_progress",
    version: "20260511100000",
    name: "activation_wizard_progress",
    file: "supabase/migrations/20260511100000_activation_wizard_progress.sql",
    legacySources: Object.freeze(["db/activation_wizard_progress.sql"]),
    tier: "feature-gated",
    note: "Adds owner-scoped activation wizard progress for the first-value setup path.",
  }),
  Object.freeze({
    id: "messages_display_mode",
    version: "20260513000000",
    name: "messages_display_mode",
    file: "supabase/migrations/20260513000000_messages_display_mode.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds page/widget display mode metadata to persisted public assistant messages.",
  }),
  Object.freeze({
    id: "full_page_assistant_config",
    version: "20260518000000",
    name: "full_page_assistant_config",
    file: "supabase/migrations/20260518000000_full_page_assistant_config.sql",
    legacySources: Object.freeze(["db/full_page_assistant_config.sql"]),
    tier: "feature-gated",
    note: "Adds full-page assistant owner customization config on widget_configs with runtime fallback for old assistants.",
  }),
  Object.freeze({
    id: "front_desk_training_items",
    version: "20260520000000",
    name: "front_desk_training_items",
    file: "supabase/migrations/20260520000000_front_desk_training_items.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-approved Front Desk training items used by the dashboard workspace and chat context retrieval.",
  }),
  Object.freeze({
    id: "extend_reply_feedback_review_loop",
    version: "20260520001000",
    name: "extend_reply_feedback_review_loop",
    file: "supabase/migrations/20260520001000_extend_reply_feedback_review_loop.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Extends assistant reply feedback with review status, owner/test sources, notes, and approved-answer linkage.",
  }),
  Object.freeze({
    id: "voice_config",
    version: "20260522000000",
    name: "voice_config",
    file: "supabase/migrations/20260522000000_voice_config.sql",
    legacySources: Object.freeze(["db/voice_config.sql"]),
    tier: "feature-gated",
    note: "Adds Phase 1 Front Desk voice input and spoken reply settings on widget_configs with safe runtime defaults.",
  }),
  Object.freeze({
    id: "front_desk_rag_chunks",
    version: "20260522001000",
    name: "front_desk_rag_chunks",
    file: "supabase/migrations/20260522001000_front_desk_rag_chunks.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds pgvector-backed semantic Front Desk knowledge chunks and scoped match RPC for owner-approved answers, business profile facts, and website context.",
  }),
  Object.freeze({
    id: "enterprise_readiness_hardening",
    version: "20260523000000",
    name: "enterprise_readiness_hardening",
    file: "supabase/migrations/20260523000000_enterprise_readiness_hardening.sql",
    legacySources: Object.freeze([]),
    tier: "required",
    note: "Adds admin audit logs, durable website import jobs, and owner-scoped policies for enterprise readiness hardening.",
  }),
  Object.freeze({
    id: "agent_booking_integrations",
    version: "20260523001000",
    name: "agent_booking_integrations",
    file: "supabase/migrations/20260523001000_agent_booking_integrations.sql",
    legacySources: Object.freeze(["db/agent_booking_integrations.sql"]),
    tier: "feature-gated",
    note: "Adds owner-scoped Calendly webhook integration storage for trusted booking confirmations.",
  }),
  Object.freeze({
    id: "phone_front_desk_phase_1b",
    version: "20260525000000",
    name: "phone_front_desk_phase_1b",
    file: "supabase/migrations/20260525000000_phone_front_desk_phase_1b.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-scoped phone number and Twilio call session storage for static Phone Front Desk webhook wiring.",
  }),
  Object.freeze({
    id: "web_call_sessions",
    version: "20260528000000",
    name: "web_call_sessions",
    file: "supabase/migrations/20260528000000_web_call_sessions.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds server-authoritative browser Web Call sessions and safe per-turn latency telemetry for full-page Front Desk voice turns.",
  }),
  Object.freeze({
    id: "realtime_web_call",
    version: "20260528001000",
    name: "realtime_web_call",
    file: "supabase/migrations/20260528001000_realtime_web_call.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds safe session-level telemetry columns for optional Realtime WebRTC Web Call connections and fallback reasons.",
  }),
  Object.freeze({
    id: "owner_product_entitlements",
    version: "20260530000000",
    name: "owner_product_entitlements",
    file: "supabase/migrations/20260530000000_owner_product_entitlements.sql",
    legacySources: Object.freeze(["db/owner_product_entitlements.sql"]),
    tier: "feature-gated",
    note: "Adds read-only owner product entitlement rows for future product packaging without changing checkout, webhooks, or access enforcement.",
  }),
  Object.freeze({
    id: "agent_package_fields",
    version: "20260601145748",
    name: "agent_package_fields",
    file: "supabase/migrations/20260601145748_agent_package_fields.sql",
    legacySources: Object.freeze([]),
    tier: "required",
    note: "Adds minimal persisted agent package identity fields, defaulting existing agents to the general Front Desk package.",
  }),
  Object.freeze({
    id: "agent_package_hotel_concierge_constraint",
    version: "20260601162000",
    name: "agent_package_hotel_concierge_constraint",
    file: "supabase/migrations/20260601162000_agent_package_hotel_concierge_constraint.sql",
    legacySources: Object.freeze([]),
    tier: "required",
    note: "Widens the agent package key constraint to allow controlled internal Hotel Concierge assignment while preserving the Front Desk default.",
  }),
  Object.freeze({
    id: "agent_action_requests",
    version: "20260601185631",
    name: "agent_action_requests",
    file: "supabase/migrations/20260601185631_agent_action_requests.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds package-neutral owner-scoped action request persistence for future package-owned workflows without runtime execution wiring.",
  }),
  Object.freeze({
    id: "agent_booking_requests",
    version: "20260602135522",
    name: "agent_booking_requests",
    file: "supabase/migrations/20260602135522_agent_booking_requests.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds generic owner-scoped booking request persistence and read-only owner RLS for future staff review workflows without public chat or provider booking behavior.",
  }),
  Object.freeze({
    id: "connected_app_connection_foundation",
    version: "20260602150000",
    name: "connected_app_connection_foundation",
    file: "supabase/migrations/20260602150000_connected_app_connection_foundation.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds generic owner-scoped connected app connection and agent enablement persistence with owner-select RLS only; no OAuth, provider execution, dashboard UI, or package activation enforcement.",
  }),
  Object.freeze({
    id: "connected_app_inbound_events",
    version: "20260603105759",
    name: "connected_app_inbound_events",
    file: "supabase/migrations/20260603105759_connected_app_inbound_events.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-scoped redacted connected app inbound event persistence for WhatsApp webhook audit/routing preparation with owner-select RLS only; no chat messages, replies, provider calls, or package activation enforcement.",
  }),
  Object.freeze({
    id: "connected_app_inbound_threads",
    version: "20260603133000",
    name: "connected_app_inbound_threads",
    file: "supabase/migrations/20260603133000_connected_app_inbound_threads.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-scoped read-only staff inbox thread grouping for redacted connected app inbound events with owner-select RLS only; no replies, AI handoff, outbound messaging, provider calls, or package activation enforcement.",
  }),
  Object.freeze({
    id: "connected_app_outbound_messages",
    version: "20260603133840",
    name: "connected_app_outbound_messages",
    file: "supabase/migrations/20260603133840_connected_app_outbound_messages.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-readable WhatsApp manual staff outbound audit rows with service/internal writes only; feature-flagged off by default and no AI, automatic, public chat, widget, embed, Meta OAuth, or Twilio WhatsApp behavior.",
  }),
  Object.freeze({
    id: "whatsapp_ai_reply_draft_context",
    version: "20260603143000",
    name: "whatsapp_ai_reply_draft_context",
    file: "supabase/migrations/20260603143000_whatsapp_ai_reply_draft_context.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds tightly constrained WhatsApp-only inbound text context for staff-approved AI reply drafts; feature-flagged off by default and no automatic replies, provider sends, public chat, widget, embed, Meta OAuth, or Twilio WhatsApp behavior.",
  }),
  Object.freeze({
    id: "agent_quote_requests",
    version: "20260604120000",
    name: "agent_quote_requests",
    file: "supabase/migrations/20260604120000_agent_quote_requests.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-scoped request-only quote intake persistence with owner-select RLS, service/internal writes, and no automatic pricing, final quote, provider, widget, or embed behavior.",
  }),
  Object.freeze({
    id: "qdh_owner_setups",
    version: "20260604143000",
    name: "qdh_owner_setups",
    file: "supabase/migrations/20260604143000_qdh_owner_setups.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-scoped Quote Desk HU setup-readiness persistence for self-serve access; no final quote calculation, external sends, provider calls, widget changes, or generic dashboard coupling.",
  }),
  Object.freeze({
    id: "enterprise_request_desk_requests",
    version: "20260605120000",
    name: "enterprise_request_desk_requests",
    file: "supabase/migrations/20260605120000_enterprise_request_desk_requests.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-scoped Enterprise Request Desk pilot request persistence with owner-select RLS, service/internal writes, request-review states only, and no QDH merge, provider calls, final quote guarantees, widget, or embed behavior.",
  }),
  Object.freeze({
    id: "enterprise_request_desk_owner_setups",
    version: "20260605153000",
    name: "enterprise_request_desk_owner_setups",
    file: "supabase/migrations/20260605153000_enterprise_request_desk_owner_setups.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds owner-scoped Enterprise Request Desk setup-readiness persistence for the standalone product shell; no QDH merge, provider calls, final pricing guarantees, widget, embed, or operations cockpit behavior.",
  }),
  Object.freeze({
    id: "widget_early_access_waitlist",
    version: "20260612110000",
    name: "widget_early_access_waitlist",
    file: "supabase/migrations/20260612110000_widget_early_access_waitlist.sql",
    legacySources: Object.freeze([]),
    tier: "feature-gated",
    note: "Adds standalone Hungarian Website Widget early-access application persistence with service-role writes only; no public Supabase read/write policy, dashboard coupling, widget, embed, chat, or billing behavior.",
  }),
]);

export const SUPABASE_MIGRATION_FILE_BY_ID = Object.freeze(
  Object.fromEntries(SUPABASE_MIGRATIONS.map((migration) => [migration.id, migration.file]))
);

export const SUPABASE_MIGRATION_IDS = Object.freeze(
  SUPABASE_MIGRATIONS.map((migration) => migration.id)
);

export const LEGACY_SOURCE_TO_SUPABASE_FILE = Object.freeze(
  Object.fromEntries(
    SUPABASE_MIGRATIONS.flatMap((migration) =>
      migration.legacySources.map((legacySource) => [legacySource, migration.file])
    )
  )
);

export function getSupabaseMigration(migrationId) {
  return SUPABASE_MIGRATIONS.find((migration) => migration.id === migrationId) || null;
}

export function getSupabaseMigrationFiles(migrationIds = []) {
  return migrationIds
    .map((migrationId) => getSupabaseMigration(migrationId)?.file || "")
    .filter(Boolean);
}

export function getSupabaseMigrationLegacySources(migrationIds = []) {
  return migrationIds.flatMap(
    (migrationId) => getSupabaseMigration(migrationId)?.legacySources || []
  );
}
